name: Manual

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: "Run with debugging enabled"
        required: false
        default: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure with CMake
        run: cmake . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Check directory
        run: dir build

      - name: Setup debugging session
        uses: mxschmitt/action-tmate@v3
        if: inputs.debug
        with:
          limit-access-to-actor: true

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ruptura.exe
          path: build/Release/ruptura.exe